package de.unisiegen.gtitool.ui.netbeans;

import java.awt.Frame;

import de.unisiegen.gtitool.ui.logic.AboutDialog;


/**
 * The {@link AboutDialogForm}.
 * 
 * @author Christian Fehler
 * @version $Id$
 */
@SuppressWarnings({ "all" })
public class AboutDialogForm extends javax.swing.JDialog {
    
    /**
     * The serial version uid.
     */
    private static final long serialVersionUID = 8264731535784921404L;
    
    /**
     * The {@link AboutDialog}.
     */
    private AboutDialog logic ;
    
    /**
     * Creates new form {@link AboutDialog}.
     * 
     * @param logic The {@link AboutDialog}.
     * @param parent The parent {@link Frame}.
     */
    public AboutDialogForm(AboutDialog logic, java.awt.Frame parent) {
        super(parent, true);
        this.logic = logic ;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelMain = new javax.swing.JPanel();
        jPanelNorth = new javax.swing.JPanel();
        jLabelIcon = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelCopyright = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jPanelSouth = new javax.swing.JPanel();
        jLabelWebpage = new javax.swing.JLabel();
        jLabelWebpageEntry = new javax.swing.JLabel();
        jLabelVersion = new javax.swing.JLabel();
        jLabelVersionEntry = new javax.swing.JLabel();
        jLabelDeveloper = new javax.swing.JLabel();
        jLabelDeveloper0 = new javax.swing.JLabel();
        jLabelDeveloper1 = new javax.swing.JLabel();
        jGTIButtonClose = new de.unisiegen.gtitool.ui.swing.JGTIButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/messages"); // NOI18N
        setTitle(bundle.getString("AboutDialog.Title")); // NOI18N
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelMain.setLayout(new java.awt.GridBagLayout());

        jPanelNorth.setLayout(new java.awt.GridBagLayout());

        jPanelNorth.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/uni_logo.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        jPanelNorth.add(jLabelIcon, gridBagConstraints);

        jLabelName.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("GTI Tool ?.?.?");
        jLabelName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelNorth.add(jLabelName, gridBagConstraints);

        jLabelCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCopyright.setText(bundle.getString("AboutDialog.Copyright")); // NOI18N
        jLabelCopyright.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelNorth.add(jLabelCopyright, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanelMain.add(jPanelNorth, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanelMain.add(jSeparator, gridBagConstraints);

        jPanelSouth.setLayout(new java.awt.GridBagLayout());

        jLabelWebpage.setText(bundle.getString("AboutDialog.Webpage")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 5, 10);
        jPanelSouth.add(jLabelWebpage, gridBagConstraints);

        jLabelWebpageEntry.setForeground(java.awt.Color.blue);
        jLabelWebpageEntry.setText("http://theoinf.math.uni-siegen.de/gtitool");
        jLabelWebpageEntry.setToolTipText(bundle.getString("AboutDialog.WebpageEntryToolTip")); // NOI18N
        jLabelWebpageEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelWebpageEntryMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        jPanelSouth.add(jLabelWebpageEntry, gridBagConstraints);

        jLabelVersion.setText(bundle.getString("AboutDialog.Version")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 10);
        jPanelSouth.add(jLabelVersion, gridBagConstraints);

        jLabelVersionEntry.setText("?.?.?.????");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanelSouth.add(jLabelVersionEntry, gridBagConstraints);

        jLabelDeveloper.setText(bundle.getString("AboutDialog.Developer")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 10);
        jPanelSouth.add(jLabelDeveloper, gridBagConstraints);

        jLabelDeveloper0.setText("Christian Fehler");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanelSouth.add(jLabelDeveloper0, gridBagConstraints);

        jLabelDeveloper1.setText("Benjamin Mies");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanelSouth.add(jLabelDeveloper1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        jPanelMain.add(jPanelSouth, gridBagConstraints);

        jGTIButtonClose.setMnemonic(java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/messages").getString("AboutDialog.CloseMnemonic").charAt(0));
        jGTIButtonClose.setText(bundle.getString("AboutDialog.Close")); // NOI18N
        jGTIButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonCloseActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 16, 16);
        jPanelMain.add(jGTIButtonClose, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelMain, gridBagConstraints);

        setSize(new java.awt.Dimension(448, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void jGTIButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonCloseActionPerformed
      this.logic.handleClose();
    }//GEN-LAST:event_jGTIButtonCloseActionPerformed

    private void jLabelWebpageEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWebpageEntryMouseClicked
      this.logic.handleWebpageEntry();
    }//GEN-LAST:event_jLabelWebpageEntryMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      this.logic.handleClose();
    }//GEN-LAST:event_formWindowClosing
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonClose;
    public javax.swing.JLabel jLabelCopyright;
    public javax.swing.JLabel jLabelDeveloper;
    private javax.swing.JLabel jLabelDeveloper0;
    private javax.swing.JLabel jLabelDeveloper1;
    private javax.swing.JLabel jLabelIcon;
    public javax.swing.JLabel jLabelName;
    public javax.swing.JLabel jLabelVersion;
    public javax.swing.JLabel jLabelVersionEntry;
    public javax.swing.JLabel jLabelWebpage;
    public javax.swing.JLabel jLabelWebpageEntry;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JSeparator jSeparator;
    // End of variables declaration//GEN-END:variables
    
}
