/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseFindParsingTableEntryGame.java
 *
 * Created on 31.03.2010, 12:30:08
 */

package de.unisiegen.gtitool.ui.netbeans;

import de.unisiegen.gtitool.ui.netbeans.interfaces.GUIClass;
import de.unisiegen.gtitool.ui.logic.ChooseFindParsingTableEntryGameDialog;

/**
 *
 * @author christian
 */
public class ChooseFindParsingTableEntryGameDialogForm extends javax.swing.JDialog
 implements GUIClass <ChooseFindParsingTableEntryGameDialog> {

    private ChooseFindParsingTableEntryGameDialog logic;

    /** Creates new form ChooseFindParsingTableEntryGame */
    public ChooseFindParsingTableEntryGameDialogForm(java.awt.Frame parent, ChooseFindParsingTableEntryGameDialog logic) {
        super(parent, true);
        this.logic = logic;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jGTIPanel1 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTIRadioButtonFindSingleEntry = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIRadioButtonFindMultipleEntries = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIPanel2 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jGTIInfoTextArea = new de.unisiegen.gtitool.ui.swing.JGTITextArea();
        jGTIInfoLabel = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTIPanel3 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTIButtonOk = new de.unisiegen.gtitool.ui.swing.JGTIButton();
        jGTIButtonCancel = new de.unisiegen.gtitool.ui.swing.JGTIButton();

        buttonGroup1.add(jGTIRadioButtonFindSingleEntry);
        buttonGroup1.add(jGTIRadioButtonFindMultipleEntries);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/i18n/messages"); // NOI18N
        jGTIRadioButtonFindSingleEntry.setText(bundle.getString("ChooseFindParsingTableEntryGameDialog.RadioButtonFindSingleEntry")); // NOI18N
        jGTIRadioButtonFindSingleEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIRadioButtonFindSingleEntryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        jGTIPanel1.add(jGTIRadioButtonFindSingleEntry, gridBagConstraints);

        jGTIRadioButtonFindMultipleEntries.setText(bundle.getString("ChooseFindParsingTableEntryGameDialog.RadioButtonFindMultipleEntries")); // NOI18N
        jGTIRadioButtonFindMultipleEntries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIRadioButtonFindMultipleEntriesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIPanel1.add(jGTIRadioButtonFindMultipleEntries, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 5, 16);
        getContentPane().add(jGTIPanel1, gridBagConstraints);

        jGTIInfoTextArea.setColumns(20);
        jGTIInfoTextArea.setRows(5);
        jScrollPane1.setViewportView(jGTIInfoTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIPanel2.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jGTIPanel2, gridBagConstraints);

        jGTIInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jGTIInfoLabel.setText(bundle.getString("ChooseFindParsingTableEntryGameDialog.LabelInfo")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(jGTIInfoLabel, gridBagConstraints);

        jGTIButtonOk.setText("Ok"); // NOI18N
        jGTIButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jGTIPanel3.add(jGTIButtonOk, gridBagConstraints);

        jGTIButtonCancel.setText(bundle.getString("ChooseFindParsingTableEntryGameDialog.ButtonCancel")); // NOI18N
        jGTIButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jGTIPanel3.add(jGTIButtonCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jGTIPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGTIButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonOkActionPerformed
        this.logic.handleOk();
    }//GEN-LAST:event_jGTIButtonOkActionPerformed

    private void jGTIButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonCancelActionPerformed
        this.logic.handleCancel();
    }//GEN-LAST:event_jGTIButtonCancelActionPerformed

    private void jGTIRadioButtonFindSingleEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIRadioButtonFindSingleEntryActionPerformed
        this.logic.handleSelectionSwitch(0);
    }//GEN-LAST:event_jGTIRadioButtonFindSingleEntryActionPerformed

    private void jGTIRadioButtonFindMultipleEntriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIRadioButtonFindMultipleEntriesActionPerformed
        this.logic.handleSelectionSwitch(1);
    }//GEN-LAST:event_jGTIRadioButtonFindMultipleEntriesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonCancel;
    private de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonOk;
    private de.unisiegen.gtitool.ui.swing.JGTILabel jGTIInfoLabel;
    public de.unisiegen.gtitool.ui.swing.JGTITextArea jGTIInfoTextArea;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel1;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel2;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel3;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonFindMultipleEntries;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonFindSingleEntry;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public ChooseFindParsingTableEntryGameDialog getLogic() {
        return this.logic;
    }

}
