/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseNextActionDialogForm.java
 *
 * Created on 10.03.2010, 14:31:01
 */

package de.unisiegen.gtitool.ui.netbeans;

import de.unisiegen.gtitool.ui.logic.ChooseNextActionDialog;
import de.unisiegen.gtitool.ui.netbeans.interfaces.GUIClass;

/**
 *
 * @author christian
 */
public class ChooseNextActionDialogForm extends javax.swing.JDialog implements GUIClass <ChooseNextActionDialog> {

    /** Creates new form ChooseNextActionDialogForm */
    public ChooseNextActionDialogForm(ChooseNextActionDialog logic, java.awt.Frame parent) {
        super(parent, true);
        this.logic = logic;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        this.jGTILabel1 = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        this.jGTIPanel1 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        this.jScrollPane1 = new javax.swing.JScrollPane();
        this.jGTIListActionList = new de.unisiegen.gtitool.ui.swing.JGTIList();
        this.jGTIButtonOk = new de.unisiegen.gtitool.ui.swing.JGTIButton();
        this.jGTIButtonCancel = new de.unisiegen.gtitool.ui.swing.JGTIButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/i18n/messages"); // NOI18N
        setTitle(bundle.getString("ChooseNextActionDialog.Title")); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        this.jGTILabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        this.jGTILabel1.setText(bundle.getString("ChooseNextActionDialog.Header")); // NOI18N
        this.jGTILabel1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(this.jGTILabel1, gridBagConstraints);

        this.jScrollPane1.setViewportView(this.jGTIListActionList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        this.jGTIPanel1.add(this.jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(this.jGTIPanel1, gridBagConstraints);

        this.jGTIButtonOk.setMnemonic(java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/i18n/messages").getString("ChooseNextActionDialog.OkMnemonic").charAt(0));
        this.jGTIButtonOk.setText(bundle.getString("ChooseNextActionDialog.Ok")); // NOI18N
        this.jGTIButtonOk.setToolTipText(bundle.getString("ChooseNextActionDialog.OkToolTip")); // NOI18N
        this.jGTIButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(this.jGTIButtonOk, gridBagConstraints);

        this.jGTIButtonCancel.setMnemonic(java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/i18n/messages").getString("ChooseNextActionDialog.CancelMnemonic").charAt(0));
        this.jGTIButtonCancel.setText(bundle.getString("ChooseNextActionDialog.Cancel")); // NOI18N
        this.jGTIButtonCancel.setToolTipText(bundle.getString("ChooseNextActionDialog.CancelToolTip")); // NOI18N
        this.jGTIButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(this.jGTIButtonCancel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGTIButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonOkActionPerformed
        this.logic.handleOk();
    }//GEN-LAST:event_jGTIButtonOkActionPerformed

    private void jGTIButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonCancelActionPerformed
        this.logic.handleCancel();
    }//GEN-LAST:event_jGTIButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonCancel;
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonOk;
    private de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabel1;
    public de.unisiegen.gtitool.ui.swing.JGTIList jGTIListActionList;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private ChooseNextActionDialog logic;

    public ChooseNextActionDialog getLogic() {
        return this.logic;
    }

}
