/*
 * ConsolePanelForm.java
 *
 * Created on 16. Dezember 2007, 17:49
 */

package de.unisiegen.gtitool.ui.netbeans;

import de.unisiegen.gtitool.ui.logic.ConsolePanel;

/**
 *
 * @author  benny
 */
public class ConsolePanelForm extends javax.swing.JPanel {
    
    /** Creates new form ConsolePanelForm */
    public ConsolePanelForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPaneConsole = new javax.swing.JTabbedPane();
        jScrollPaneErrors = new javax.swing.JScrollPane();
        jTableErrors = new javax.swing.JTable();
        jScrollPaneWarnings = new javax.swing.JScrollPane();
        jTableWarnings = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        jTabbedPaneConsole.setFocusable(false);
        jTableErrors.setFocusable(false);
        jTableErrors.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTableErrorsMouseMoved(evt);
            }
        });
        jTableErrors.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableErrorsFocusLost(evt);
            }
        });
        jTableErrors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTableErrorsMouseExited(evt);
            }
        });

        jScrollPaneErrors.setViewportView(jTableErrors);

        jTabbedPaneConsole.addTab("Error", new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/error.gif")), jScrollPaneErrors);

        jTableWarnings.setFocusable(false);
        jTableWarnings.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTableWarningsMouseMoved(evt);
            }
        });
        jTableWarnings.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableWarningsFocusLost(evt);
            }
        });
        jTableWarnings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTableWarningsMouseExited(evt);
            }
        });

        jScrollPaneWarnings.setViewportView(jTableWarnings);

        jTabbedPaneConsole.addTab("Warning", new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/warning.gif")), jScrollPaneWarnings);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jTabbedPaneConsole, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void jTableWarningsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableWarningsMouseExited
        this.logic.handleConsoleTableMouseExited( evt );
    }//GEN-LAST:event_jTableWarningsMouseExited

    private void jTableWarningsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableWarningsFocusLost
        this.logic.handleConsoleTableFocusLost(evt);
    }//GEN-LAST:event_jTableWarningsFocusLost

    private void jTableWarningsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableWarningsMouseMoved
        this.logic.handleConsoleTableMouseMoved(evt);
    }//GEN-LAST:event_jTableWarningsMouseMoved

    private void jTableErrorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableErrorsMouseExited
        this.logic.handleConsoleTableMouseExited( evt );
    }//GEN-LAST:event_jTableErrorsMouseExited

    private void jTableErrorsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableErrorsFocusLost
        this.logic.handleConsoleTableFocusLost(evt);
    }//GEN-LAST:event_jTableErrorsFocusLost

    private void jTableErrorsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableErrorsMouseMoved
        this.logic.handleConsoleTableMouseMoved(evt);
    }//GEN-LAST:event_jTableErrorsMouseMoved
    
    
    // Variablendeklaration - nicht modifizieren//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPaneErrors;
    public javax.swing.JScrollPane jScrollPaneWarnings;
    public javax.swing.JTabbedPane jTabbedPaneConsole;
    public javax.swing.JTable jTableErrors;
    public javax.swing.JTable jTableWarnings;
    // Ende der Variablendeklaration//GEN-END:variables
    
    private ConsolePanel logic;
    
    public void setLogic ( ConsolePanel pLogic ){
      this.logic = pLogic;
    }
}
