/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateParsingTableForm.java
 *
 * Created on 18.03.2010, 13:06:47
 */

package de.unisiegen.gtitool.ui.netbeans;

import de.unisiegen.gtitool.ui.logic.CreateParsingTableDialog;
import de.unisiegen.gtitool.ui.netbeans.interfaces.GUIClass;

/**
 *
 * @author Christian Uhrhan
 */
public class CreateParsingTableDialogForm extends javax.swing.JDialog implements GUIClass<CreateParsingTableDialog>{

  private CreateParsingTableDialog logic;
  
    /** Creates new form CreateParsingTableForm */
    public CreateParsingTableDialogForm(java.awt.Frame parent, CreateParsingTableDialog logic) {
        super(parent, true);
        this.logic = logic;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jGTIGrammarPanel = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTIPanel1 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTILabelTerminalSymbols = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTILabelStartSymbol = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTILabelNonterminalSymbols = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        styledNonterminalSymbolSetParserPanel = new de.unisiegen.gtitool.ui.style.StyledNonterminalSymbolSetParserPanel();
        styledStartNonterminalSymbolParserPanel = new de.unisiegen.gtitool.ui.style.StyledStartNonterminalSymbolParserPanel();
        styledTerminalSymbolSetParserPanel = new de.unisiegen.gtitool.ui.style.StyledTerminalSymbolSetParserPanel();
        jGTIPanel2 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTIScrollPane1 = new de.unisiegen.gtitool.ui.swing.JGTIScrollPane();
        jGTIGrammarTable = new de.unisiegen.gtitool.ui.swing.JGTITable();
        jGTIToolBar = new de.unisiegen.gtitool.ui.swing.JGTIToolBar();
        jGTIToolBarButtonStart = new de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton();
        jGTIToolBarButtonPreviousStep = new de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton();
        jGTIToolBarButtonNextStep = new de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton();
        jGTIToolBarToggleButtonAutoStep = new de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarToggleButton();
        jGTIToolBarButtonStop = new de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton();
        jGTIParsingTablePanel = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTICurrentNonterminalLabel = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTICurrentTerminalLabel = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTIPanel3 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTILabel3 = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTIScrollPane2 = new de.unisiegen.gtitool.ui.swing.JGTIScrollPane();
        jGTIParsingTable = new de.unisiegen.gtitool.ui.swing.JGTITable();
        jGTIPanel4 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTILabel4 = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTIScrollPane3 = new de.unisiegen.gtitool.ui.swing.JGTIScrollPane();
        jGTIDescriptionList = new de.unisiegen.gtitool.ui.swing.JGTIList();
        jGTIStatusLabel = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTIButtonOk = new de.unisiegen.gtitool.ui.swing.JGTIButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/i18n/messages"); // NOI18N
        jGTILabelTerminalSymbols.setText(bundle.getString("CreateParsingTableDialog.LabelTerminalSymbols")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        jGTIPanel1.add(jGTILabelTerminalSymbols, gridBagConstraints);

        jGTILabelStartSymbol.setText(bundle.getString("CreateParsingTableDialog.LabelStartSymbol")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        jGTIPanel1.add(jGTILabelStartSymbol, gridBagConstraints);

        jGTILabelNonterminalSymbols.setText(bundle.getString("CreateParsingTableDialog.LabelNonterminalSymbols")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 5, 16);
        jGTIPanel1.add(jGTILabelNonterminalSymbols, gridBagConstraints);

        styledNonterminalSymbolSetParserPanel.setCopyable(true);
        styledNonterminalSymbolSetParserPanel.setEditable(false);
        styledNonterminalSymbolSetParserPanel.setMinimumSize(new java.awt.Dimension(49, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 16);
        jGTIPanel1.add(styledNonterminalSymbolSetParserPanel, gridBagConstraints);

        styledStartNonterminalSymbolParserPanel.setCopyable(true);
        styledStartNonterminalSymbolParserPanel.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 16);
        jGTIPanel1.add(styledStartNonterminalSymbolParserPanel, gridBagConstraints);

        styledTerminalSymbolSetParserPanel.setCopyable(true);
        styledTerminalSymbolSetParserPanel.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 16, 16);
        jGTIPanel1.add(styledTerminalSymbolSetParserPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIGrammarPanel.add(jGTIPanel1, gridBagConstraints);

        jGTIGrammarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jGTIScrollPane1.setViewportView(jGTIGrammarTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIPanel2.add(jGTIScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIGrammarPanel.add(jGTIPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jGTIGrammarPanel, gridBagConstraints);

        jGTIToolBar.setRollover(true);

        jGTIToolBarButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/navigation/large/start.png"))); // NOI18N
        jGTIToolBarButtonStart.setToolTipText(bundle.getString("MachinePanel.WordModeStart")); // NOI18N
        jGTIToolBarButtonStart.setFocusable(false);
        jGTIToolBarButtonStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jGTIToolBarButtonStart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jGTIToolBarButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIToolBarButtonStartActionPerformed(evt);
            }
        });
        jGTIToolBar.add(jGTIToolBarButtonStart);

        jGTIToolBarButtonPreviousStep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/navigation/large/backward.png"))); // NOI18N
        jGTIToolBarButtonPreviousStep.setToolTipText(bundle.getString("MachinePanel.WordModePreviousStep")); // NOI18N
        jGTIToolBarButtonPreviousStep.setEnabled(false);
        jGTIToolBarButtonPreviousStep.setFocusable(false);
        jGTIToolBarButtonPreviousStep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jGTIToolBarButtonPreviousStep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jGTIToolBarButtonPreviousStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIToolBarButtonPreviousStepActionPerformed(evt);
            }
        });
        jGTIToolBar.add(jGTIToolBarButtonPreviousStep);

        jGTIToolBarButtonNextStep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/navigation/large/forward.png"))); // NOI18N
        jGTIToolBarButtonNextStep.setToolTipText(bundle.getString("MachinePanel.WordModeNextStep")); // NOI18N
        jGTIToolBarButtonNextStep.setEnabled(false);
        jGTIToolBarButtonNextStep.setFocusable(false);
        jGTIToolBarButtonNextStep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jGTIToolBarButtonNextStep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jGTIToolBarButtonNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIToolBarButtonNextStepActionPerformed(evt);
            }
        });
        jGTIToolBar.add(jGTIToolBarButtonNextStep);

        jGTIToolBarToggleButtonAutoStep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/navigation/large/autostep.png"))); // NOI18N
        jGTIToolBarToggleButtonAutoStep.setToolTipText(bundle.getString("MachinePanel.WordModeAutoStep")); // NOI18N
        jGTIToolBarToggleButtonAutoStep.setEnabled(false);
        jGTIToolBarToggleButtonAutoStep.setFocusable(false);
        jGTIToolBarToggleButtonAutoStep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jGTIToolBarToggleButtonAutoStep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jGTIToolBarToggleButtonAutoStep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jGTIToolBarToggleButtonAutoStepItemStateChanged(evt);
            }
        });
        jGTIToolBar.add(jGTIToolBarToggleButtonAutoStep);

        jGTIToolBarButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/navigation/large/stop.png"))); // NOI18N
        jGTIToolBarButtonStop.setToolTipText(bundle.getString("MachinePanel.WordModeStop")); // NOI18N
        jGTIToolBarButtonStop.setEnabled(false);
        jGTIToolBarButtonStop.setFocusable(false);
        jGTIToolBarButtonStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jGTIToolBarButtonStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jGTIToolBarButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIToolBarButtonStopActionPerformed(evt);
            }
        });
        jGTIToolBar.add(jGTIToolBarButtonStop);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jGTIToolBar, gridBagConstraints);

        jGTICurrentNonterminalLabel.setText(bundle.getString("CreateParsingTableDialog.CurrentNonterminal")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jGTIParsingTablePanel.add(jGTICurrentNonterminalLabel, gridBagConstraints);

        jGTICurrentTerminalLabel.setText(bundle.getString("CreateParsingTableDialog.CurrentTerminal")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jGTIParsingTablePanel.add(jGTICurrentTerminalLabel, gridBagConstraints);

        jGTILabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jGTILabel3.setText(bundle.getString("CreateParsingTableDialog.LabelParsingTable")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jGTIPanel3.add(jGTILabel3, gridBagConstraints);

        jGTIParsingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jGTIScrollPane2.setViewportView(jGTIParsingTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIPanel3.add(jGTIScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIParsingTablePanel.add(jGTIPanel3, gridBagConstraints);

        jGTILabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jGTILabel4.setText(bundle.getString("CreateParsingTableDialog.LabelDescription")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jGTIPanel4.add(jGTILabel4, gridBagConstraints);

        jGTIScrollPane3.setViewportView(jGTIDescriptionList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIPanel4.add(jGTIScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIParsingTablePanel.add(jGTIPanel4, gridBagConstraints);

        jGTIStatusLabel.setText(bundle.getString("CreateParsingTableDialog.LabelStatus")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jGTIParsingTablePanel.add(jGTIStatusLabel, gridBagConstraints);

        jGTIButtonOk.setText("Ok");
        jGTIButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jGTIParsingTablePanel.add(jGTIButtonOk, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jGTIParsingTablePanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGTIToolBarButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIToolBarButtonStartActionPerformed
        this.logic.handleStart();
}//GEN-LAST:event_jGTIToolBarButtonStartActionPerformed

    private void jGTIToolBarButtonPreviousStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIToolBarButtonPreviousStepActionPerformed
        this.logic.handlePrevious();
}//GEN-LAST:event_jGTIToolBarButtonPreviousStepActionPerformed

    private void jGTIToolBarButtonNextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIToolBarButtonNextStepActionPerformed
        this.logic.handleNext();
}//GEN-LAST:event_jGTIToolBarButtonNextStepActionPerformed

    private void jGTIToolBarToggleButtonAutoStepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jGTIToolBarToggleButtonAutoStepItemStateChanged
        this.logic.handleAutoStep();
}//GEN-LAST:event_jGTIToolBarToggleButtonAutoStepItemStateChanged

    private void jGTIToolBarButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIToolBarButtonStopActionPerformed
        this.logic.handleStop();
}//GEN-LAST:event_jGTIToolBarButtonStopActionPerformed

    private void jGTIButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonOkActionPerformed
        this.logic.handleOk();
    }//GEN-LAST:event_jGTIButtonOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonOk;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTICurrentNonterminalLabel;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTICurrentTerminalLabel;
    public de.unisiegen.gtitool.ui.swing.JGTIList jGTIDescriptionList;
    public de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIGrammarPanel;
    public de.unisiegen.gtitool.ui.swing.JGTITable jGTIGrammarTable;
    private de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabel3;
    private de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabel4;
    private de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelNonterminalSymbols;
    private de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelStartSymbol;
    private de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelTerminalSymbols;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel1;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel2;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel3;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel4;
    public de.unisiegen.gtitool.ui.swing.JGTITable jGTIParsingTable;
    public de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIParsingTablePanel;
    private de.unisiegen.gtitool.ui.swing.JGTIScrollPane jGTIScrollPane1;
    private de.unisiegen.gtitool.ui.swing.JGTIScrollPane jGTIScrollPane2;
    private de.unisiegen.gtitool.ui.swing.JGTIScrollPane jGTIScrollPane3;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTIStatusLabel;
    public de.unisiegen.gtitool.ui.swing.JGTIToolBar jGTIToolBar;
    public de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton jGTIToolBarButtonNextStep;
    public de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton jGTIToolBarButtonPreviousStep;
    public de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton jGTIToolBarButtonStart;
    public de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton jGTIToolBarButtonStop;
    public de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarToggleButton jGTIToolBarToggleButtonAutoStep;
    public de.unisiegen.gtitool.ui.style.StyledNonterminalSymbolSetParserPanel styledNonterminalSymbolSetParserPanel;
    public de.unisiegen.gtitool.ui.style.StyledStartNonterminalSymbolParserPanel styledStartNonterminalSymbolParserPanel;
    public de.unisiegen.gtitool.ui.style.StyledTerminalSymbolSetParserPanel styledTerminalSymbolSetParserPanel;
    // End of variables declaration//GEN-END:variables
    /**
     * {@inheritDoc}
     * 
     * @see de.unisiegen.gtitool.ui.netbeans.interfaces.GUIClass#getLogic()
     */
    public CreateParsingTableDialog getLogic ()
    {
      return this.logic;
    }

}
