/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateParsingTableGameDialogForm.java
 *
 * Created on 29.03.2010, 12:40:18
 */

package de.unisiegen.gtitool.ui.netbeans;

import de.unisiegen.gtitool.ui.logic.CreateParsingTableGameDialog;
import de.unisiegen.gtitool.ui.netbeans.interfaces.GUIClass;

/**
 *
 * @author christian
 */
public class CreateParsingTableGameDialogForm extends javax.swing.JDialog
    implements GUIClass<CreateParsingTableGameDialog> {

    private CreateParsingTableGameDialog logic;

    /** Creates new form CreateParsingTableGameDialogForm */
    public CreateParsingTableGameDialogForm(java.awt.Frame parent, CreateParsingTableGameDialog logic) {
        super(parent, true);
        this.logic = logic;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jGTIFirstFollowPanel = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jGTIFirstSetTable = new de.unisiegen.gtitool.ui.swing.JGTITable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jGTIFollowSetTable = new de.unisiegen.gtitool.ui.swing.JGTITable();
        jGTISeparator1 = new de.unisiegen.gtitool.ui.swing.JGTISeparator();
        jGTIPanel4 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTIExistingCorrectAnswersLabel = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTIExistingWrongAnswersLabel = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTICorrectAnswersLabel = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTIWrongAnswersLabel = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTIPanel3 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTIScrollPane2 = new de.unisiegen.gtitool.ui.swing.JGTIScrollPane();
        jGTIParsingTable = new de.unisiegen.gtitool.ui.swing.JGTITable();
        jGTIButtonOk = new de.unisiegen.gtitool.ui.swing.JGTIButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/i18n/messages"); // NOI18N
        setTitle(bundle.getString("CreateParsingTableGameDialog.Caption")); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jGTIFirstSetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jGTIFirstSetTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIFirstFollowPanel.add(jScrollPane1, gridBagConstraints);

        jGTIFollowSetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jGTIFollowSetTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIFirstFollowPanel.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 5, 16);
        getContentPane().add(jGTIFirstFollowPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jGTISeparator1, gridBagConstraints);

        jGTIExistingCorrectAnswersLabel.setText("jGTILabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jGTIPanel4.add(jGTIExistingCorrectAnswersLabel, gridBagConstraints);

        jGTIExistingWrongAnswersLabel.setText("jGTILabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jGTIPanel4.add(jGTIExistingWrongAnswersLabel, gridBagConstraints);

        jGTICorrectAnswersLabel.setText("jGTILabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jGTIPanel4.add(jGTICorrectAnswersLabel, gridBagConstraints);

        jGTIWrongAnswersLabel.setText("jGTILabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jGTIPanel4.add(jGTIWrongAnswersLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jGTIPanel4, gridBagConstraints);

        jGTIParsingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jGTIParsingTable.setColumnSelectionAllowed(true);
        jGTIParsingTable.getTableHeader().setReorderingAllowed(false);
        jGTIParsingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGTIParsingTableMouseClicked(evt);
            }
        });
        jGTIScrollPane2.setViewportView(jGTIParsingTable);
        jGTIParsingTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 5, 16);
        jGTIPanel3.add(jGTIScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jGTIPanel3, gridBagConstraints);

        jGTIButtonOk.setText("Ok");
        jGTIButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jGTIButtonOk, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGTIButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonOkActionPerformed
        this.logic.handleOk();
    }//GEN-LAST:event_jGTIButtonOkActionPerformed

    private void jGTIParsingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGTIParsingTableMouseClicked
        this.logic.handleUncover(evt);
    }//GEN-LAST:event_jGTIParsingTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonOk;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTICorrectAnswersLabel;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTIExistingCorrectAnswersLabel;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTIExistingWrongAnswersLabel;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIFirstFollowPanel;
    public de.unisiegen.gtitool.ui.swing.JGTITable jGTIFirstSetTable;
    public de.unisiegen.gtitool.ui.swing.JGTITable jGTIFollowSetTable;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel3;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel4;
    public de.unisiegen.gtitool.ui.swing.JGTITable jGTIParsingTable;
    private de.unisiegen.gtitool.ui.swing.JGTIScrollPane jGTIScrollPane2;
    private de.unisiegen.gtitool.ui.swing.JGTISeparator jGTISeparator1;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTIWrongAnswersLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public CreateParsingTableGameDialog getLogic() {
        return this.logic;
    }

}
