package de.unisiegen.gtitool.ui.netbeans;

import java.awt.Frame;

import de.unisiegen.gtitool.ui.logic.AboutDialog;
import de.unisiegen.gtitool.ui.logic.ExchangeDialog;

/**
 * The {@link AboutDialogForm}.
 * 
 * @author Christian Fehler
 * @version $Id$
 */
@SuppressWarnings({ "all" })
public class ExchangeDialogForm extends javax.swing.JDialog {
    
  /**
   * The serial version uid.
   */
  private static final long serialVersionUID = 4187569542433797162L;


  /**
   * The {@link ExchangeDialog}.
   */
  private ExchangeDialog logic;


  /**
   * Creates new form {@link ExchangeDialog}.
   * 
   * @param logic The {@link ExchangeDialog}.
   * @param parent The parent {@link Frame}.
   */
  public ExchangeDialogForm ( ExchangeDialog logic, java.awt.Frame parent )
  {
    super ( parent, true );
    this.logic = logic;
    initComponents ();
  }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPaneStatus = new javax.swing.JScrollPane();
        jTextPaneStatus = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldHost = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        jGTIButtonSend = new de.unisiegen.gtitool.ui.swing.JGTIButton();
        jGTIButtonReceive = new de.unisiegen.gtitool.ui.swing.JGTIButton();
        jGTIButtonClose = new de.unisiegen.gtitool.ui.swing.JGTIButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("*Title*");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPaneStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextPaneStatus.setBorder(null);
        jTextPaneStatus.setEditable(false);
        jTextPaneStatus.setFocusable(false);
        jScrollPaneStatus.setViewportView(jTextPaneStatus);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 5, 16);
        getContentPane().add(jScrollPaneStatus, gridBagConstraints);

        jLabel1.setText("*Host*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        jTextFieldHost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 16);
        getContentPane().add(jTextFieldHost, gridBagConstraints);

        jPanelButtons.setLayout(new java.awt.GridBagLayout());

        jGTIButtonSend.setText("*Send*");
        jGTIButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonSendActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanelButtons.add(jGTIButtonSend, gridBagConstraints);

        jGTIButtonReceive.setText("*Receive*");
        jGTIButtonReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonReceiveActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanelButtons.add(jGTIButtonReceive, gridBagConstraints);

        jGTIButtonClose.setText("*Close*");
        jGTIButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonCloseActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanelButtons.add(jGTIButtonClose, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 16, 16);
        getContentPane().add(jPanelButtons, gridBagConstraints);

        setBounds(0, 0, 400, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void jGTIButtonReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonReceiveActionPerformed
      this.logic.handleReceive();
    }//GEN-LAST:event_jGTIButtonReceiveActionPerformed

    private void jGTIButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonSendActionPerformed
      this.logic.handleSend();
    }//GEN-LAST:event_jGTIButtonSendActionPerformed

    private void jGTIButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonCloseActionPerformed
      this.logic.handleClose();
    }//GEN-LAST:event_jGTIButtonCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      this.logic.handleClose();
    }//GEN-LAST:event_formWindowClosing
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonClose;
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonReceive;
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonSend;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanelButtons;
    public javax.swing.JScrollPane jScrollPaneStatus;
    public javax.swing.JTextField jTextFieldHost;
    public javax.swing.JTextPane jTextPaneStatus;
    // End of variables declaration//GEN-END:variables
}
