/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FirstSetDialogForm.java
 *
 * Created on 27.04.2010, 13:44:02
 */

package de.unisiegen.gtitool.ui.netbeans;

import de.unisiegen.gtitool.ui.logic.FirstSetDialog;
import de.unisiegen.gtitool.ui.netbeans.interfaces.GUIClass;

/**
 *
 * @author christian
 */
public class FirstSetDialogForm extends javax.swing.JDialog implements GUIClass<FirstSetDialog> {

    /** Creates new form FirstSetDialogForm */
    public FirstSetDialogForm(java.awt.Frame parent, FirstSetDialog logic) {
        super(parent, true);
        this.logic = logic;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jGTIPanel1 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTIToolBar2 = new de.unisiegen.gtitool.ui.swing.JGTIToolBar();
        jGTIToolBarButtonStart2 = new de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton();
        jGTIToolBarButtonPreviousStep = new de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton();
        jGTIToolBarButtonNextStep = new de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton();
        jGTIToolBarButtonStop = new de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton();
        jGTIPanel2 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jGTIFirstTable = new de.unisiegen.gtitool.ui.swing.JGTITable();
        jGTIButtonOk = new de.unisiegen.gtitool.ui.swing.JGTIButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/i18n/messages"); // NOI18N
        setTitle(bundle.getString("FirstSetDialog.Caption")); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jGTIToolBar2.setRollover(true);

        jGTIToolBarButtonStart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/navigation/large/start.png"))); // NOI18N
        jGTIToolBarButtonStart2.setToolTipText(bundle.getString("MachinePanel.WordModeStart")); // NOI18N
        jGTIToolBarButtonStart2.setFocusable(false);
        jGTIToolBarButtonStart2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jGTIToolBarButtonStart2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jGTIToolBarButtonStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIToolBarButtonStart2ActionPerformed(evt);
            }
        });
        jGTIToolBar2.add(jGTIToolBarButtonStart2);

        jGTIToolBarButtonPreviousStep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/navigation/large/backward.png"))); // NOI18N
        jGTIToolBarButtonPreviousStep.setToolTipText(bundle.getString("MachinePanel.WordModePreviousStep")); // NOI18N
        jGTIToolBarButtonPreviousStep.setEnabled(false);
        jGTIToolBarButtonPreviousStep.setFocusable(false);
        jGTIToolBarButtonPreviousStep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jGTIToolBarButtonPreviousStep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jGTIToolBarButtonPreviousStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIToolBarButtonPreviousStepActionPerformed(evt);
            }
        });
        jGTIToolBar2.add(jGTIToolBarButtonPreviousStep);

        jGTIToolBarButtonNextStep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/navigation/large/forward.png"))); // NOI18N
        jGTIToolBarButtonNextStep.setToolTipText(bundle.getString("MachinePanel.WordModeNextStep")); // NOI18N
        jGTIToolBarButtonNextStep.setEnabled(false);
        jGTIToolBarButtonNextStep.setFocusable(false);
        jGTIToolBarButtonNextStep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jGTIToolBarButtonNextStep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jGTIToolBarButtonNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIToolBarButtonNextStepActionPerformed(evt);
            }
        });
        jGTIToolBar2.add(jGTIToolBarButtonNextStep);

        jGTIToolBarButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/navigation/large/stop.png"))); // NOI18N
        jGTIToolBarButtonStop.setToolTipText(bundle.getString("MachinePanel.WordModeStop")); // NOI18N
        jGTIToolBarButtonStop.setEnabled(false);
        jGTIToolBarButtonStop.setFocusable(false);
        jGTIToolBarButtonStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jGTIToolBarButtonStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jGTIToolBarButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIToolBarButtonStopActionPerformed(evt);
            }
        });
        jGTIToolBar2.add(jGTIToolBarButtonStop);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        jGTIPanel1.add(jGTIToolBar2, gridBagConstraints);

        jGTIFirstTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jGTIFirstTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIPanel2.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIPanel1.add(jGTIPanel2, gridBagConstraints);

        jGTIButtonOk.setText("Ok");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jGTIPanel1.add(jGTIButtonOk, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 5, 15);
        getContentPane().add(jGTIPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGTIToolBarButtonStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIToolBarButtonStart2ActionPerformed
        this.logic.handleStart();
}//GEN-LAST:event_jGTIToolBarButtonStart2ActionPerformed

    private void jGTIToolBarButtonPreviousStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIToolBarButtonPreviousStepActionPerformed
        this.logic.handlePrevious();
}//GEN-LAST:event_jGTIToolBarButtonPreviousStepActionPerformed

    private void jGTIToolBarButtonNextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIToolBarButtonNextStepActionPerformed
        this.logic.handleNext();
}//GEN-LAST:event_jGTIToolBarButtonNextStepActionPerformed

    private void jGTIToolBarButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIToolBarButtonStopActionPerformed
        this.logic.handleStop();
}//GEN-LAST:event_jGTIToolBarButtonStopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonOk;
    public de.unisiegen.gtitool.ui.swing.JGTITable jGTIFirstTable;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel1;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel2;
    private de.unisiegen.gtitool.ui.swing.JGTIToolBar jGTIToolBar;
    private de.unisiegen.gtitool.ui.swing.JGTIToolBar jGTIToolBar1;
    public de.unisiegen.gtitool.ui.swing.JGTIToolBar jGTIToolBar2;
    public de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton jGTIToolBarButtonNextStep;
    public de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton jGTIToolBarButtonPreviousStep;
    public de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton jGTIToolBarButtonStart;
    public de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton jGTIToolBarButtonStart1;
    public de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton jGTIToolBarButtonStart2;
    public de.unisiegen.gtitool.ui.swing.specialized.JGTIToolBarButton jGTIToolBarButtonStop;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private FirstSetDialog logic;

    public FirstSetDialog getLogic() {
        return this.logic;
    }

}
