package de.unisiegen.gtitool.ui.netbeans;

import javax.swing.JPanel;

/**
 * The {@link LicensePanel}.
 * 
 * @author Benjamin Mies
 * @author Christian Fehler
 * @version $Id: AboutDialogForm.java 1002 2008-06-15 15:48:22Z mies $
 */
@SuppressWarnings({ "all" })
public class LicensePanel extends JPanel
{

    /**
     * The serial version uid.
     */
    private static final long serialVersionUID = -4059754769638808201L;


    /**
     * Allocates a new {@link LicensePanel}.
     */
    public LicensePanel ()
    {
      initComponents ();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jGTIScrollPaneLicense = new de.unisiegen.gtitool.ui.swing.JGTIScrollPane();
        jGTITextAreaLicense = new de.unisiegen.gtitool.ui.swing.JGTITextArea();

        setLayout(new java.awt.GridBagLayout());

        jGTITextAreaLicense.setColumns(20);
        jGTITextAreaLicense.setEditable(false);
        jGTITextAreaLicense.setRows(5);
        jGTITextAreaLicense.setFocusable(false);
        jGTIScrollPaneLicense.setViewportView(jGTITextAreaLicense);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        add(jGTIScrollPaneLicense, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public de.unisiegen.gtitool.ui.swing.JGTIScrollPane jGTIScrollPaneLicense;
    public de.unisiegen.gtitool.ui.swing.JGTITextArea jGTITextAreaLicense;
    // End of variables declaration//GEN-END:variables
    
}
