package de.unisiegen.gtitool.ui.netbeans;

import de.unisiegen.gtitool.ui.EditorPanel;
import de.unisiegen.gtitool.ui.logic.MachinePanel;
import de.unisiegen.gtitool.ui.netbeans.helperclasses.EditorPanelForm;

/**
 * The Forms file for the {@link MachinePanel}
 *
 * @author Benjamin Mies
 * @version $Id$
 */
@SuppressWarnings({ "all" })
public class MachinePanelForm extends javax.swing.JPanel implements EditorPanelForm{
    
    /** Creates new form MachinesPanelForm */
    public MachinePanelForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        toolbarButton = new javax.swing.ButtonGroup();
        jSplitPaneConsole = new javax.swing.JSplitPane();
        jPanelTop = new javax.swing.JPanel();
        jSplitPaneTable = new javax.swing.JSplitPane();
        jPanelDiagramm = new javax.swing.JPanel();
        diagrammContentPanel = new javax.swing.JScrollPane();
        jPanelTable = new javax.swing.JPanel();
        jScrollPaneMachine = new javax.swing.JScrollPane();
        jGTITableMachine = new de.unisiegen.gtitool.ui.swing.JGTITable();
        jPanelBottom = new javax.swing.JPanel();
        jTabbedPaneConsole = new javax.swing.JTabbedPane();
        jScrollPaneErrors = new javax.swing.JScrollPane();
        jGTITableErrors = new de.unisiegen.gtitool.ui.swing.JGTITable();
        jScrollPaneWarnings = new javax.swing.JScrollPane();
        jGTITableWarnings = new de.unisiegen.gtitool.ui.swing.JGTITable();
        wordPanel = new de.unisiegen.gtitool.ui.netbeans.WordPanelForm();

        setLayout(new java.awt.GridBagLayout());

        jSplitPaneConsole.setDividerLocation(200);
        jSplitPaneConsole.setDividerSize(3);
        jSplitPaneConsole.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPaneConsole.setResizeWeight(1.0);
        jPanelTop.setLayout(new java.awt.GridBagLayout());

        jSplitPaneTable.setDividerLocation(400);
        jSplitPaneTable.setDividerSize(3);
        jSplitPaneTable.setResizeWeight(1.0);
        jPanelDiagramm.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelDiagramm.add(diagrammContentPanel, gridBagConstraints);

        jSplitPaneTable.setLeftComponent(jPanelDiagramm);

        jPanelTable.setLayout(new java.awt.GridBagLayout());

        jGTITableMachine.setFocusable(false);
        jGTITableMachine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jGTITableMachineMouseExited(evt);
            }
        });
        jGTITableMachine.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jGTITableMachineFocusLost(evt);
            }
        });

        jScrollPaneMachine.setViewportView(jGTITableMachine);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTable.add(jScrollPaneMachine, gridBagConstraints);

        jSplitPaneTable.setRightComponent(jPanelTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelTop.add(jSplitPaneTable, gridBagConstraints);

        jSplitPaneConsole.setLeftComponent(jPanelTop);

        jPanelBottom.setLayout(new java.awt.GridBagLayout());

        jTabbedPaneConsole.setFocusable(false);
        jGTITableErrors.setFocusable(false);
        jGTITableErrors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jGTITableErrorsMouseExited(evt);
            }
        });
        jGTITableErrors.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jGTITableErrorsFocusLost(evt);
            }
        });

        jScrollPaneErrors.setViewportView(jGTITableErrors);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/messages"); // NOI18N
        jTabbedPaneConsole.addTab(bundle.getString("MachinePanel.Error"), new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/error.gif")), jScrollPaneErrors); // NOI18N

        jGTITableWarnings.setFocusable(false);
        jGTITableWarnings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jGTITableWarningsMouseExited(evt);
            }
        });
        jGTITableWarnings.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jGTITableWarningsFocusLost(evt);
            }
        });

        jScrollPaneWarnings.setViewportView(jGTITableWarnings);

        jTabbedPaneConsole.addTab(bundle.getString("MachinePanel.Warning"), new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/warning.gif")), jScrollPaneWarnings); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelBottom.add(jTabbedPaneConsole, gridBagConstraints);

        jSplitPaneConsole.setRightComponent(jPanelBottom);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jSplitPaneConsole, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(wordPanel, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void jGTITableMachineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGTITableMachineMouseExited
      this.logic.handleMachineTableMouseExited(evt);
    }//GEN-LAST:event_jGTITableMachineMouseExited

    private void jGTITableMachineFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jGTITableMachineFocusLost
      this.logic.handleMachineTableFocusLost(evt);
    }//GEN-LAST:event_jGTITableMachineFocusLost

    private void jGTITableErrorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGTITableErrorsMouseExited
      this.logic.handleConsoleTableMouseExited ( evt );
    }//GEN-LAST:event_jGTITableErrorsMouseExited

    private void jGTITableWarningsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGTITableWarningsMouseExited
      this.logic.handleConsoleTableMouseExited ( evt );
    }//GEN-LAST:event_jGTITableWarningsMouseExited

    private void jGTITableWarningsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jGTITableWarningsFocusLost
      this.logic.handleConsoleTableFocusLost(evt);
    }//GEN-LAST:event_jGTITableWarningsFocusLost

    private void jGTITableErrorsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jGTITableErrorsFocusLost
      this.logic.handleConsoleTableFocusLost(evt);
    }//GEN-LAST:event_jGTITableErrorsFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane diagrammContentPanel;
    public de.unisiegen.gtitool.ui.swing.JGTITable jGTITableErrors;
    public de.unisiegen.gtitool.ui.swing.JGTITable jGTITableMachine;
    public de.unisiegen.gtitool.ui.swing.JGTITable jGTITableWarnings;
    public javax.swing.JPanel jPanelBottom;
    public javax.swing.JPanel jPanelDiagramm;
    public javax.swing.JPanel jPanelTable;
    public javax.swing.JPanel jPanelTop;
    public javax.swing.JScrollPane jScrollPaneErrors;
    public javax.swing.JScrollPane jScrollPaneMachine;
    public javax.swing.JScrollPane jScrollPaneWarnings;
    public javax.swing.JSplitPane jSplitPaneConsole;
    public javax.swing.JSplitPane jSplitPaneTable;
    public javax.swing.JTabbedPane jTabbedPaneConsole;
    public javax.swing.ButtonGroup toolbarButton;
    public de.unisiegen.gtitool.ui.netbeans.WordPanelForm wordPanel;
    // End of variables declaration//GEN-END:variables
    
    
    private MachinePanel logic;
    
    public void setMachinePanel (MachinePanel window){
        logic = window;
    }
    
    public MachinePanel getLogic(){
      return this.logic;
    }
}


