/*
 * FileWizard.java
 *
 * Created on 26. Juli 2006, 19:44
 */

package de.unisiegen.gtitool.ui.netbeans;

import de.unisiegen.gtitool.ui.logic.NewDialog;



/**
 *
 * @author Benjamin Mies
 * @version $Id: NewDialog.java 119 2007-11-10 12:07:30Z fehler 
 */
public class NewDialogForm extends javax.swing.JDialog {

  //
  // Constructor
  //
  
  /**
   * Allocates a new <code>FileWizard</code> instance.
   *
   * @param parent the parent frame.
   * @param modal <code>true</code> to display the wizard modal
   *              for the <code>parent</code>.
   */
  public NewDialogForm(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    
    initComponents();
   
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JPanel buttonsPanel;
        javax.swing.JButton cancelButton;
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JLabel headerImageLabel;
        javax.swing.JPanel headerPanel;
        javax.swing.JLabel headerSubTitleLabel;
        javax.swing.JLabel headerTitleLabel;
        javax.swing.JPanel tabbedPanel;

        machines = new javax.swing.ButtonGroup();
        grammars = new javax.swing.ButtonGroup();
        headerPanel = new javax.swing.JPanel();
        headerTitleLabel = new javax.swing.JLabel();
        headerSubTitleLabel = new javax.swing.JLabel();
        headerImageLabel = new javax.swing.JLabel();
        tabbedPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        machinesPanel = new javax.swing.JPanel();
        jLabelMachinesCaption = new javax.swing.JLabel();
        buttonMachinesPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanelMachinesSpace = new javax.swing.JPanel();
        bodyPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextPaneMachineAlphabet = new javax.swing.JTextPane();
        grammarsPanel = new javax.swing.JPanel();
        jLabelGrammarsCaption = new javax.swing.JLabel();
        buttonGrammarsPanel = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jPanelGrammarsSpace = new javax.swing.JPanel();
        bodyPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextPaneGrammarAlphabet = new javax.swing.JTextPane();
        buttonsPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("newDialog");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerTitleLabel.setFont(new java.awt.Font("Dialog", 1, 24));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/messages"); // NOI18N
        headerTitleLabel.setText(bundle.getString("MainWindow.New")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        headerPanel.add(headerTitleLabel, gridBagConstraints);

        headerSubTitleLabel.setText(bundle.getString("NewDialog.NewSubtitle")); // NOI18N
        headerSubTitleLabel.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        headerPanel.add(headerSubTitleLabel, gridBagConstraints);

        headerImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/new24.png")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        headerPanel.add(headerImageLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        getContentPane().add(headerPanel, gridBagConstraints);

        tabbedPanel.setLayout(new java.awt.GridBagLayout());

        tabbedPane.setName("machines");
        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneStateChanged(evt);
            }
        });
        tabbedPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabbedPaneKeyPressed(evt);
            }
        });

        machinesPanel.setLayout(new java.awt.GridBagLayout());

        machinesPanel.setPreferredSize(new java.awt.Dimension(329, 100));
        jLabelMachinesCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMachinesCaption.setText(bundle.getString("NewDialog.ChooseMachine")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 15, 0);
        machinesPanel.add(jLabelMachinesCaption, gridBagConstraints);

        buttonMachinesPanel.setLayout(new java.awt.GridBagLayout());

        machines.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Kellerautomat");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        buttonMachinesPanel.add(jRadioButton1, gridBagConstraints);

        machines.add(jRadioButton2);
        jRadioButton2.setText("NDEA");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        buttonMachinesPanel.add(jRadioButton2, gridBagConstraints);

        machines.add(jRadioButton3);
        jRadioButton3.setText("DEA");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        buttonMachinesPanel.add(jRadioButton3, gridBagConstraints);

        machines.add(jRadioButton4);
        jRadioButton4.setText("e-NDEA");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        buttonMachinesPanel.add(jRadioButton4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        machinesPanel.add(buttonMachinesPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        machinesPanel.add(jPanelMachinesSpace, gridBagConstraints);

        bodyPanel.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText(bundle.getString("NewDialog.ChooseAlphabet")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        bodyPanel.add(jLabel5, gridBagConstraints);

        jTextPaneMachineAlphabet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextPaneMachineAlphabet.setMaximumSize(new java.awt.Dimension(6, 46));
        jTextPaneMachineAlphabet.setMinimumSize(new java.awt.Dimension(6, 46));
        jTextPaneMachineAlphabet.setPreferredSize(new java.awt.Dimension(6, 46));
        jTextPaneMachineAlphabet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                handleKeyTypedEvent(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 20, 40);
        bodyPanel.add(jTextPaneMachineAlphabet, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        machinesPanel.add(bodyPanel, gridBagConstraints);

        tabbedPane.addTab(bundle.getString("NewDialog.Machine"), machinesPanel); // NOI18N

        grammarsPanel.setLayout(new java.awt.GridBagLayout());

        jLabelGrammarsCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGrammarsCaption.setText(bundle.getString("NewDialog.ChooseGrammar")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 15, 0);
        grammarsPanel.add(jLabelGrammarsCaption, gridBagConstraints);

        buttonGrammarsPanel.setLayout(new java.awt.GridBagLayout());

        grammars.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("regul\u00e4re Grammatik");
        jRadioButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        buttonGrammarsPanel.add(jRadioButton5, gridBagConstraints);

        grammars.add(jRadioButton6);
        jRadioButton6.setText("kontextfreie Grammatik");
        jRadioButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        buttonGrammarsPanel.add(jRadioButton6, gridBagConstraints);

        grammars.add(jRadioButton7);
        jRadioButton7.setText("kontextsensitive Grammatik");
        jRadioButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        buttonGrammarsPanel.add(jRadioButton7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        grammarsPanel.add(buttonGrammarsPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        grammarsPanel.add(jPanelGrammarsSpace, gridBagConstraints);

        bodyPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText(bundle.getString("NewDialog.ChooseAlphabet")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        bodyPanel1.add(jLabel4, gridBagConstraints);

        jTextPaneGrammarAlphabet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextPaneGrammarAlphabet.setMaximumSize(new java.awt.Dimension(6, 46));
        jTextPaneGrammarAlphabet.setMinimumSize(new java.awt.Dimension(6, 46));
        jTextPaneGrammarAlphabet.setPreferredSize(new java.awt.Dimension(6, 46));
        jTextPaneGrammarAlphabet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                handleKeyTypedEvent(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 20, 40);
        bodyPanel1.add(jTextPaneGrammarAlphabet, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        grammarsPanel.add(bodyPanel1, gridBagConstraints);

        tabbedPane.addTab(bundle.getString("NewDialog.Grammar"), grammarsPanel); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 2.0;
        tabbedPanel.add(tabbedPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 10.0;
        getContentPane().add(tabbedPanel, gridBagConstraints);

        buttonsPanel.setLayout(new java.awt.GridBagLayout());

        cancelButton.setText(bundle.getString("Cancel")); // NOI18N
        cancelButton.setLabel(bundle.getString("Cancel")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        buttonsPanel.add(cancelButton, gridBagConstraints);

        okButton.setMnemonic('O');
        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        buttonsPanel.add(okButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(buttonsPanel, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-515)/2, (screenSize.height-400)/2, 515, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void handleKeyTypedEvent(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_handleKeyTypedEvent
        this.logic.handleKeyTypedEvent( evt ) ;
    }//GEN-LAST:event_handleKeyTypedEvent

    private void tabbedPaneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabbedPaneKeyPressed
// NOTICE Ihre Ereignisbehandlung hier einfügen:
    }//GEN-LAST:event_tabbedPaneKeyPressed

    private void tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPaneStateChanged
// NOTICE Ihre Ereignisbehandlung hier einfügen:
    }//GEN-LAST:event_tabbedPaneStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// NOTICE Ihre Ereignisbehandlung hier einfügen:
    }//GEN-LAST:event_formWindowClosing

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
// NOTICE Ihre Ereignisbehandlung hier einfügen:
      this.canceled = false;
      dispose();
    }//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
// NOTICE Ihre Ereignisbehandlung hier einfügen:
     this.canceled =  true;
      dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed
  
    // Variablendeklaration - nicht modifizieren//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel bodyPanel1;
    private javax.swing.JPanel buttonGrammarsPanel;
    private javax.swing.JPanel buttonMachinesPanel;
    private javax.swing.ButtonGroup grammars;
    private javax.swing.JPanel grammarsPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelGrammarsCaption;
    private javax.swing.JLabel jLabelMachinesCaption;
    private javax.swing.JPanel jPanelGrammarsSpace;
    private javax.swing.JPanel jPanelMachinesSpace;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    public javax.swing.JTextPane jTextPaneGrammarAlphabet;
    public javax.swing.JTextPane jTextPaneMachineAlphabet;
    private javax.swing.ButtonGroup machines;
    public javax.swing.JPanel machinesPanel;
    public javax.swing.JButton okButton;
    public javax.swing.JTabbedPane tabbedPane;
    // Ende der Variablendeklaration//GEN-END:variables
    
    private NewDialog logic;
    
    private boolean canceled = true;
    
    public void setLogic( NewDialog pLogic){
        this.logic = pLogic;
    }
    
    public boolean isCanceled(){
        return this.canceled;
    }
}
