/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jPanelParsingTableGrammarPanel.java
 *
 * Created on 29.03.2010, 10:52:43
 */

package de.unisiegen.gtitool.ui.netbeans;

/**
 *
 * @author christian
 */
public class ParsingTableGrammarPanel extends javax.swing.JPanel {

    /** Creates new form jPanelParsingTableGrammarPanel */
    public ParsingTableGrammarPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jGTIPanel1 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTILabelTerminalSymbols = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTILabelStartSymbol = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTILabelNonterminalSymbols = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        styledNonterminalSymbolSetParserPanel = new de.unisiegen.gtitool.ui.style.StyledNonterminalSymbolSetParserPanel();
        styledStartNonterminalSymbolParserPanel = new de.unisiegen.gtitool.ui.style.StyledStartNonterminalSymbolParserPanel();
        styledTerminalSymbolSetParserPanel = new de.unisiegen.gtitool.ui.style.StyledTerminalSymbolSetParserPanel();
        jGTIPanel2 = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTIScrollPane1 = new de.unisiegen.gtitool.ui.swing.JGTIScrollPane();
        jGTIGrammarTable = new de.unisiegen.gtitool.ui.swing.JGTITable();

        setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/i18n/messages"); // NOI18N
        jGTILabelTerminalSymbols.setText(bundle.getString("CreateParsingTableDialog.LabelTerminalSymbols")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        jGTIPanel1.add(jGTILabelTerminalSymbols, gridBagConstraints);

        jGTILabelStartSymbol.setText(bundle.getString("CreateParsingTableDialog.LabelStartSymbol")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        jGTIPanel1.add(jGTILabelStartSymbol, gridBagConstraints);

        jGTILabelNonterminalSymbols.setText(bundle.getString("CreateParsingTableDialog.LabelNonterminalSymbols")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 5, 16);
        jGTIPanel1.add(jGTILabelNonterminalSymbols, gridBagConstraints);

        styledNonterminalSymbolSetParserPanel.setCopyable(true);
        styledNonterminalSymbolSetParserPanel.setEditable(false);
        styledNonterminalSymbolSetParserPanel.setMinimumSize(new java.awt.Dimension(49, 29));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 16);
        jGTIPanel1.add(styledNonterminalSymbolSetParserPanel, gridBagConstraints);

        styledStartNonterminalSymbolParserPanel.setCopyable(true);
        styledStartNonterminalSymbolParserPanel.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 16);
        jGTIPanel1.add(styledStartNonterminalSymbolParserPanel, gridBagConstraints);

        styledTerminalSymbolSetParserPanel.setCopyable(true);
        styledTerminalSymbolSetParserPanel.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 16, 16);
        jGTIPanel1.add(styledTerminalSymbolSetParserPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jGTIPanel1, gridBagConstraints);

        jGTIGrammarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jGTIScrollPane1.setViewportView(jGTIGrammarTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jGTIPanel2.add(jGTIScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jGTIPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public de.unisiegen.gtitool.ui.swing.JGTITable jGTIGrammarTable;
    private de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelNonterminalSymbols;
    private de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelStartSymbol;
    private de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelTerminalSymbols;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel1;
    private de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanel2;
    private de.unisiegen.gtitool.ui.swing.JGTIScrollPane jGTIScrollPane1;
    public de.unisiegen.gtitool.ui.style.StyledNonterminalSymbolSetParserPanel styledNonterminalSymbolSetParserPanel;
    public de.unisiegen.gtitool.ui.style.StyledStartNonterminalSymbolParserPanel styledStartNonterminalSymbolParserPanel;
    public de.unisiegen.gtitool.ui.style.StyledTerminalSymbolSetParserPanel styledTerminalSymbolSetParserPanel;
    // End of variables declaration//GEN-END:variables

}
