package de.unisiegen.gtitool.ui.netbeans;

import de.unisiegen.gtitool.ui.logic.PreferencesDialog;

/**
 * The <code>PreferencesDialogForm</code>.
 * 
 * @author Christian Fehler
 * @version $Id$
 */
@SuppressWarnings({"all"})
public class PreferencesDialogForm extends javax.swing.JDialog {
    
    /*
     * The {@link PreferencesDialog}.
     */
    private PreferencesDialog preferencesDialog ;
    
    /** Creates new form PreferenceDialog */
    public PreferencesDialogForm(PreferencesDialog pPreferencesDialog, java.awt.Frame parent) {
        super(parent, true);
        this.preferencesDialog = pPreferencesDialog;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelGeneral = new javax.swing.JPanel();
        jPanelColors = new javax.swing.JPanel();
        jScrollPaneColor = new javax.swing.JScrollPane();
        jListColor = new javax.swing.JList();
        jButtonClose = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/messages"); // NOI18N
        setTitle(bundle.getString("PreferencesDialog.Title")); // NOI18N
        setModal(true);
        jTabbedPane.setFocusable(false);
        jPanelGeneral.setLayout(new java.awt.GridBagLayout());

        jTabbedPane.addTab(bundle.getString("PreferencesDialog.TabGeneral"), jPanelGeneral); // NOI18N

        jPanelColors.setLayout(new java.awt.GridBagLayout());

        jListColor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneColor.setViewportView(jListColor);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelColors.add(jScrollPaneColor, gridBagConstraints);

        jTabbedPane.addTab(bundle.getString("PreferencesDialog.TabColors"), jPanelColors); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jTabbedPane, gridBagConstraints);

        jButtonClose.setText(bundle.getString("PreferencesDialog.Close")); // NOI18N
        jButtonClose.setFocusable(false);
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(jButtonClose, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.preferencesDialog.close();
    }//GEN-LAST:event_jButtonCloseActionPerformed
    
    // Variablendeklaration - nicht modifizieren//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    public javax.swing.JList jListColor;
    private javax.swing.JPanel jPanelColors;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JScrollPane jScrollPaneColor;
    private javax.swing.JTabbedPane jTabbedPane;
    // Ende der Variablendeklaration//GEN-END:variables
    
}
