/*
 * PrintDialog.java
 *
 * Created on June 25, 2008, 4:44 PM
 */

package de.unisiegen.gtitool.ui.netbeans;

import java.awt.Frame;

import de.unisiegen.gtitool.ui.logic.PrintDialog;
import de.unisiegen.gtitool.ui.netbeans.interfaces.GUIClass;

/**
 * The {@link PrintDialogForm}.
 * 
 * @author Benjamin Mies
 * @version $Id$
 */
@SuppressWarnings("all")
public class PrintDialogForm extends javax.swing.JDialog implements GUIClass < PrintDialog > {

  
    /**
     * The serial version UID.
     */
    private static final long serialVersionUID = -4448708879986070934L;
  
  
    /**
     * The {@link PrintDialog}.
     */
    private PrintDialog logic;
  
  
    /** 
     * Creates new form PrintDialog
     * 
     * @param logic The {@link PrintDialog}. 
     * @param parent The parent {@link Frame}.
     **/
    public PrintDialogForm ( PrintDialog logic, Frame parent )
    {
      super ( parent, true );
      this.logic = logic;
      initComponents ();
      this.jGTIRadioButtonMachineGraph.setVisible(false);
      this.jGTIRadioButtonMachinePDATable.setVisible(false);
      this.jGTIRadioButtonMachineTable.setVisible(false);
      this.jGTIRadioButtonConvertMachineConvertedGraph.setVisible(false);
      this.jGTIRadioButtonConvertMachineOriginalGraph.setVisible(false);
      this.jGTIRadioButtonConvertedMachineTable.setVisible(false); 
      this.jGTIRadioButtonMinimizeMachineMinimizedGraph.setVisible(false);
      this.jGTIRadioButtonMinimizeMachineOriginalGraph.setVisible(false);
      this.jGTIRadioButtonMinimizeMachineTable.setVisible(false);
    }
    
    /**
     * {@inheritDoc}
     * 
     * @see de.unisiegen.gtitool.ui.netbeans.interfaces.GUIClass#getLogic()
     */
    public PrintDialog getLogic ()
    {
      return this.logic;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupMachinePanel = new javax.swing.ButtonGroup();
        buttonGroupPageFormat = new javax.swing.ButtonGroup();
        buttonGroupConvertMachine = new javax.swing.ButtonGroup();
        buttonGroupMininizeMachine = new javax.swing.ButtonGroup();
        jGTIPanelOuter = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTIPanelPrinter = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTILabelPrinter = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTIComboBoxPrinter = new de.unisiegen.gtitool.ui.swing.JGTIComboBox();
        jGTIRadioButtonMachineGraph = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIRadioButtonMachineTable = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIRadioButtonMachinePDATable = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIRadioButtonConvertMachineOriginalGraph = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIRadioButtonConvertMachineConvertedGraph = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIRadioButtonConvertedMachineTable = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIRadioButtonMinimizeMachineTable = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIRadioButtonMinimizeMachineMinimizedGraph = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIRadioButtonMinimizeMachineOriginalGraph = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIPanelPageSetup = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jPanelFormat = new javax.swing.JPanel();
        jGTILabelPortraitIcon = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jGTIRadioButtonPortrait = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTIRadioLandscape = new de.unisiegen.gtitool.ui.swing.JGTIRadioButton();
        jGTILabelLandscapeIcon = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        jPanelMargins = new javax.swing.JPanel();
        jLabelMarginLeft = new javax.swing.JLabel();
        jSpinnerMarginLeft = new javax.swing.JSpinner();
        jLabelMarginRight = new javax.swing.JLabel();
        jSpinnerMarginRight = new javax.swing.JSpinner();
        jLabelMarginTop = new javax.swing.JLabel();
        jSpinnerMarginTop = new javax.swing.JSpinner();
        jLabelMarginBottom = new javax.swing.JLabel();
        jSpinnerMarginBottom = new javax.swing.JSpinner();
        jGTIPanelButton = new de.unisiegen.gtitool.ui.swing.JGTIPanel();
        jGTIButtonCancel = new de.unisiegen.gtitool.ui.swing.JGTIButton();
        jGTIButtonYes = new de.unisiegen.gtitool.ui.swing.JGTIButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/i18n/messages"); // NOI18N
        setTitle(bundle.getString("PrintDialog.Print")); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jGTIPanelOuter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jGTIPanelPrinter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jGTILabelPrinter.setText(bundle.getString("PrintDialog.Printer")); // NOI18N
        jGTILabelPrinter.setPreferredSize(new java.awt.Dimension(100, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPrinter.add(jGTILabelPrinter, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPrinter.add(jGTIComboBoxPrinter, gridBagConstraints);

        buttonGroupMachinePanel.add(jGTIRadioButtonMachineGraph);
        jGTIRadioButtonMachineGraph.setSelected(true);
        jGTIRadioButtonMachineGraph.setText(bundle.getString("PrintDialog.PrintMachine")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPrinter.add(jGTIRadioButtonMachineGraph, gridBagConstraints);

        buttonGroupMachinePanel.add(jGTIRadioButtonMachineTable);
        jGTIRadioButtonMachineTable.setText(bundle.getString("PrintDialog.PrintTable")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPrinter.add(jGTIRadioButtonMachineTable, gridBagConstraints);

        buttonGroupMachinePanel.add(jGTIRadioButtonMachinePDATable);
        jGTIRadioButtonMachinePDATable.setText(bundle.getString("PrintDialog.PrintPrintPDATable")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPrinter.add(jGTIRadioButtonMachinePDATable, gridBagConstraints);

        buttonGroupConvertMachine.add(jGTIRadioButtonConvertMachineOriginalGraph);
        jGTIRadioButtonConvertMachineOriginalGraph.setSelected(true);
        jGTIRadioButtonConvertMachineOriginalGraph.setText(bundle.getString("PrintDialog.ConvertMachineOriginalGraph")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPrinter.add(jGTIRadioButtonConvertMachineOriginalGraph, gridBagConstraints);

        buttonGroupConvertMachine.add(jGTIRadioButtonConvertMachineConvertedGraph);
        jGTIRadioButtonConvertMachineConvertedGraph.setText(bundle.getString("PrintDialog.ConvertMachineConvertedGraph")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPrinter.add(jGTIRadioButtonConvertMachineConvertedGraph, gridBagConstraints);

        buttonGroupConvertMachine.add(jGTIRadioButtonConvertedMachineTable);
        jGTIRadioButtonConvertedMachineTable.setText(bundle.getString("PrintDialog.ConvertMachineTable")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPrinter.add(jGTIRadioButtonConvertedMachineTable, gridBagConstraints);

        buttonGroupMininizeMachine.add(jGTIRadioButtonMinimizeMachineTable);
        jGTIRadioButtonMinimizeMachineTable.setText(bundle.getString("PrintDialog.MinimizeMachineTable")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPrinter.add(jGTIRadioButtonMinimizeMachineTable, gridBagConstraints);

        buttonGroupMininizeMachine.add(jGTIRadioButtonMinimizeMachineMinimizedGraph);
        jGTIRadioButtonMinimizeMachineMinimizedGraph.setText(bundle.getString("PrintDialog.MinimizeMachineMinimizedGraph")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPrinter.add(jGTIRadioButtonMinimizeMachineMinimizedGraph, gridBagConstraints);

        buttonGroupMininizeMachine.add(jGTIRadioButtonMinimizeMachineOriginalGraph);
        jGTIRadioButtonMinimizeMachineOriginalGraph.setSelected(true);
        jGTIRadioButtonMinimizeMachineOriginalGraph.setText(bundle.getString("PrintDialog.MinimizeMachineOriginalGraph")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPrinter.add(jGTIRadioButtonMinimizeMachineOriginalGraph, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jGTIPanelOuter.add(jGTIPanelPrinter, gridBagConstraints);

        jGTIPanelPageSetup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelFormat.setLayout(new java.awt.GridBagLayout());

        jGTILabelPortraitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/portrait.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 20, 3, 5);
        jPanelFormat.add(jGTILabelPortraitIcon, gridBagConstraints);

        buttonGroupPageFormat.add(jGTIRadioButtonPortrait);
        jGTIRadioButtonPortrait.setSelected(true);
        jGTIRadioButtonPortrait.setText(bundle.getString("PrintDialog.Portrait")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 0);
        jPanelFormat.add(jGTIRadioButtonPortrait, gridBagConstraints);

        buttonGroupPageFormat.add(jGTIRadioLandscape);
        jGTIRadioLandscape.setText(bundle.getString("PrintDialog.Landscape")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 0);
        jPanelFormat.add(jGTIRadioLandscape, gridBagConstraints);

        jGTILabelLandscapeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/landscape.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 20, 3, 5);
        jPanelFormat.add(jGTILabelLandscapeIcon, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPageSetup.add(jPanelFormat, gridBagConstraints);

        jPanelMargins.setLayout(new java.awt.GridBagLayout());

        jLabelMarginLeft.setText(bundle.getString("PrintDialog.MarginLeft")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 5);
        jPanelMargins.add(jLabelMarginLeft, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        jPanelMargins.add(jSpinnerMarginLeft, gridBagConstraints);

        jLabelMarginRight.setText(bundle.getString("PrintDialog.MarginRight")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        jPanelMargins.add(jLabelMarginRight, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 0);
        jPanelMargins.add(jSpinnerMarginRight, gridBagConstraints);

        jLabelMarginTop.setText(bundle.getString("PrintDialog.MarginTop")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 5);
        jPanelMargins.add(jLabelMarginTop, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        jPanelMargins.add(jSpinnerMarginTop, gridBagConstraints);

        jLabelMarginBottom.setText(bundle.getString("PrintDialog.MarginBottom")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        jPanelMargins.add(jLabelMarginBottom, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 0);
        jPanelMargins.add(jSpinnerMarginBottom, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jGTIPanelPageSetup.add(jPanelMargins, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        jGTIPanelOuter.add(jGTIPanelPageSetup, gridBagConstraints);

        jGTIButtonCancel.setText(bundle.getString("ConfirmDialog.Cancel")); // NOI18N
        jGTIButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jGTIPanelButton.add(jGTIButtonCancel, gridBagConstraints);

        jGTIButtonYes.setText(bundle.getString("PrintDialog.Print")); // NOI18N
        jGTIButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonPrintActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jGTIPanelButton.add(jGTIButtonYes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 16, 16);
        jGTIPanelOuter.add(jGTIPanelButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        getContentPane().add(jGTIPanelOuter, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jGTIButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {this.logic.handleCancel();//GEN-FIRST:event_jGTIButtonCancelActionPerformed
}//GEN-LAST:event_jGTIButtonCancelActionPerformed

private void jGTIButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonPrintActionPerformed
this.logic.handlePrint();
}//GEN-LAST:event_jGTIButtonPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroupConvertMachine;
    public javax.swing.ButtonGroup buttonGroupMachinePanel;
    public javax.swing.ButtonGroup buttonGroupMininizeMachine;
    public javax.swing.ButtonGroup buttonGroupPageFormat;
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonCancel;
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonYes;
    public de.unisiegen.gtitool.ui.swing.JGTIComboBox jGTIComboBoxPrinter;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelLandscapeIcon;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelPortraitIcon;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelPrinter;
    public de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanelButton;
    public de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanelOuter;
    public de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanelPageSetup;
    public de.unisiegen.gtitool.ui.swing.JGTIPanel jGTIPanelPrinter;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonConvertMachineConvertedGraph;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonConvertMachineOriginalGraph;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonConvertedMachineTable;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonMachineGraph;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonMachinePDATable;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonMachineTable;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonMinimizeMachineMinimizedGraph;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonMinimizeMachineOriginalGraph;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonMinimizeMachineTable;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioButtonPortrait;
    public de.unisiegen.gtitool.ui.swing.JGTIRadioButton jGTIRadioLandscape;
    public javax.swing.JLabel jLabelMarginBottom;
    public javax.swing.JLabel jLabelMarginLeft;
    public javax.swing.JLabel jLabelMarginRight;
    public javax.swing.JLabel jLabelMarginTop;
    public javax.swing.JPanel jPanelFormat;
    public javax.swing.JPanel jPanelMargins;
    public javax.swing.JSpinner jSpinnerMarginBottom;
    public javax.swing.JSpinner jSpinnerMarginLeft;
    public javax.swing.JSpinner jSpinnerMarginRight;
    public javax.swing.JSpinner jSpinnerMarginTop;
    // End of variables declaration//GEN-END:variables


}
