package de.unisiegen.gtitool.ui.netbeans;

import java.awt.Frame;

import de.unisiegen.gtitool.ui.logic.TransitionDialog;

/**
 * The transition dialog.
 * 
 * @author Benjamin Mies
 * @author Christian Fehler
 * @version $Id$
 */
@SuppressWarnings({ "all" })
public class TransitionDialogForm extends javax.swing.JDialog {
    
   /**
    * The serial version uid.
    */
    private static final long serialVersionUID = 8316002721568381761L;
    
    /**
     * The {@link TransitionDialog}.
     */
    private TransitionDialog logic;
    
    /**
     * Creates new form <code>TransitionDialog</code>.
     * 
     * @param pLogic The {@link TransitionDialog}.
     * @param pParent The parent {@link Frame}.
     */
    public TransitionDialogForm(TransitionDialog pLogic, java.awt.Frame pParent) {
        super(pParent, true);
        this.logic = pLogic;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JLabelHeadline = new javax.swing.JLabel();
        jLabelAlphabet = new javax.swing.JLabel();
        jLabelChangeOverSet = new javax.swing.JLabel();
        jScrollPaneAlphabet = new javax.swing.JScrollPane();
        jGTIListAlphabet = new de.unisiegen.gtitool.ui.swing.JGTIList();
        jPanelChangeOverButtons = new javax.swing.JPanel();
        jButtonMoveLeft = new javax.swing.JButton();
        jButtonMoveRight = new javax.swing.JButton();
        jScrollPaneChangeOverSet = new javax.swing.JScrollPane();
        jGTIListChangeOverSet = new de.unisiegen.gtitool.ui.swing.JGTIList();
        jLabeStackRead = new javax.swing.JLabel();
        jLabelWrite = new javax.swing.JLabel();
        styledWordParserPanelRead = new de.unisiegen.gtitool.ui.style.StyledWordParserPanel();
        styledWordParserPanelWrite = new de.unisiegen.gtitool.ui.style.StyledWordParserPanel();
        JLabelTransitionSet = new javax.swing.JLabel();
        styledTransitionParserPanel = new de.unisiegen.gtitool.ui.style.StyledTransitionParserPanel();
        jPanelButtons = new javax.swing.JPanel();
        jGTIButtonOk = new de.unisiegen.gtitool.ui.swing.JGTIButton();
        jGTIButtonCancel = new de.unisiegen.gtitool.ui.swing.JGTIButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/messages"); // NOI18N
        setTitle(bundle.getString("TransitionDialog.Title")); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        JLabelHeadline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelHeadline.setText(bundle.getString("TransitionDialog.Header")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 5, 16);
        getContentPane().add(JLabelHeadline, gridBagConstraints);

        jLabelAlphabet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAlphabet.setText(bundle.getString("TransitionDialog.Alphabet")); // NOI18N
        jLabelAlphabet.setPreferredSize(new java.awt.Dimension(100, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        getContentPane().add(jLabelAlphabet, gridBagConstraints);

        jLabelChangeOverSet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelChangeOverSet.setText(bundle.getString("TransitionDialog.TransitionSet")); // NOI18N
        jLabelChangeOverSet.setPreferredSize(new java.awt.Dimension(100, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        getContentPane().add(jLabelChangeOverSet, gridBagConstraints);

        jScrollPaneAlphabet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPaneAlphabet.setPreferredSize(new java.awt.Dimension(100, 130));
        jGTIListAlphabet.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jGTIListAlphabetValueChanged(evt);
            }
        });

        jScrollPaneAlphabet.setViewportView(jGTIListAlphabet);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        getContentPane().add(jScrollPaneAlphabet, gridBagConstraints);

        jPanelChangeOverButtons.setLayout(new java.awt.GridBagLayout());

        jButtonMoveLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/moveLeft.png")));
        jButtonMoveLeft.setEnabled(false);
        jButtonMoveLeft.setFocusable(false);
        jButtonMoveLeft.setMaximumSize(new java.awt.Dimension(32, 32));
        jButtonMoveLeft.setMinimumSize(new java.awt.Dimension(32, 32));
        jButtonMoveLeft.setPreferredSize(new java.awt.Dimension(32, 32));
        jButtonMoveLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleActionPerformedMoveLeft(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanelChangeOverButtons.add(jButtonMoveLeft, gridBagConstraints);

        jButtonMoveRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/unisiegen/gtitool/ui/icon/moveRight.png")));
        jButtonMoveRight.setEnabled(false);
        jButtonMoveRight.setFocusable(false);
        jButtonMoveRight.setMaximumSize(new java.awt.Dimension(32, 32));
        jButtonMoveRight.setMinimumSize(new java.awt.Dimension(32, 32));
        jButtonMoveRight.setPreferredSize(new java.awt.Dimension(32, 32));
        jButtonMoveRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleActionPerformedMoveRight(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanelChangeOverButtons.add(jButtonMoveRight, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        getContentPane().add(jPanelChangeOverButtons, gridBagConstraints);

        jScrollPaneChangeOverSet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPaneChangeOverSet.setPreferredSize(new java.awt.Dimension(100, 130));
        jGTIListChangeOverSet.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jGTIListChangeOverSetValueChanged(evt);
            }
        });

        jScrollPaneChangeOverSet.setViewportView(jGTIListChangeOverSet);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        getContentPane().add(jScrollPaneChangeOverSet, gridBagConstraints);

        jLabeStackRead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeStackRead.setText(bundle.getString("TransitionDialog.PushDownWordRead")); // NOI18N
        jLabeStackRead.setPreferredSize(new java.awt.Dimension(100, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        getContentPane().add(jLabeStackRead, gridBagConstraints);

        jLabelWrite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWrite.setText(bundle.getString("TransitionDialog.PushDownWordWrite")); // NOI18N
        jLabelWrite.setPreferredSize(new java.awt.Dimension(100, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        getContentPane().add(jLabelWrite, gridBagConstraints);

        styledWordParserPanelRead.setMinimumSize(new java.awt.Dimension(40, 40));
        styledWordParserPanelRead.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 16);
        getContentPane().add(styledWordParserPanelRead, gridBagConstraints);

        styledWordParserPanelWrite.setMinimumSize(new java.awt.Dimension(40, 40));
        styledWordParserPanelWrite.setPreferredSize(new java.awt.Dimension(40, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 16);
        getContentPane().add(styledWordParserPanelWrite, gridBagConstraints);

        JLabelTransitionSet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelTransitionSet.setText(bundle.getString("TransitionDialog.ResultingTransitionSet")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        getContentPane().add(JLabelTransitionSet, gridBagConstraints);

        styledTransitionParserPanel.setEditable(false);
        styledTransitionParserPanel.setMinimumSize(new java.awt.Dimension(40, 40));
        styledTransitionParserPanel.setPreferredSize(new java.awt.Dimension(40, 40));
        styledTransitionParserPanel.setSideBarVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 5, 16);
        getContentPane().add(styledTransitionParserPanel, gridBagConstraints);

        jPanelButtons.setLayout(new java.awt.GridBagLayout());

        jGTIButtonOk.setMnemonic(java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/messages").getString("TransitionDialog.OkMnemonic").charAt(0));
        jGTIButtonOk.setText(bundle.getString("TransitionDialog.Ok")); // NOI18N
        jGTIButtonOk.setToolTipText(bundle.getString("TransitionDialog.OkToolTip")); // NOI18N
        jGTIButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonOkActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanelButtons.add(jGTIButtonOk, gridBagConstraints);

        jGTIButtonCancel.setMnemonic(java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/messages").getString("TransitionDialog.CancelMnemonic").charAt(0));
        jGTIButtonCancel.setText(bundle.getString("TransitionDialog.Cancel")); // NOI18N
        jGTIButtonCancel.setToolTipText(bundle.getString("TransitionDialog.CancelToolTip")); // NOI18N
        jGTIButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGTIButtonCancelActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanelButtons.add(jGTIButtonCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 16, 16, 16);
        getContentPane().add(jPanelButtons, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-440)/2, (screenSize.height-480)/2, 440, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void jGTIListChangeOverSetValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jGTIListChangeOverSetValueChanged
        this.logic.handleListSelection(evt);
    }//GEN-LAST:event_jGTIListChangeOverSetValueChanged

    private void jGTIListAlphabetValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jGTIListAlphabetValueChanged
        this.logic.handleListSelection(evt);
    }//GEN-LAST:event_jGTIListAlphabetValueChanged

    private void jGTIButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonCancelActionPerformed
        this.logic.handleCancel();
    }//GEN-LAST:event_jGTIButtonCancelActionPerformed

    private void jGTIButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGTIButtonOkActionPerformed
        this.logic.handleOk();
    }//GEN-LAST:event_jGTIButtonOkActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.logic.handleCancel();
    }//GEN-LAST:event_formWindowClosing

    private void handleActionPerformedMoveLeft(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleActionPerformedMoveLeft
        this.logic.handleMoveLeft();
    }//GEN-LAST:event_handleActionPerformedMoveLeft

    private void handleActionPerformedMoveRight(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleActionPerformedMoveRight
        this.logic.handleMoveRight();
    }//GEN-LAST:event_handleActionPerformedMoveRight

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JLabelHeadline;
    public javax.swing.JLabel JLabelTransitionSet;
    public javax.swing.JButton jButtonMoveLeft;
    public javax.swing.JButton jButtonMoveRight;
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonCancel;
    public de.unisiegen.gtitool.ui.swing.JGTIButton jGTIButtonOk;
    public de.unisiegen.gtitool.ui.swing.JGTIList jGTIListAlphabet;
    public de.unisiegen.gtitool.ui.swing.JGTIList jGTIListChangeOverSet;
    public javax.swing.JLabel jLabeStackRead;
    public javax.swing.JLabel jLabelAlphabet;
    public javax.swing.JLabel jLabelChangeOverSet;
    public javax.swing.JLabel jLabelWrite;
    public javax.swing.JPanel jPanelButtons;
    public javax.swing.JPanel jPanelChangeOverButtons;
    public javax.swing.JScrollPane jScrollPaneAlphabet;
    public javax.swing.JScrollPane jScrollPaneChangeOverSet;
    public de.unisiegen.gtitool.ui.style.StyledTransitionParserPanel styledTransitionParserPanel;
    public de.unisiegen.gtitool.ui.style.StyledWordParserPanel styledWordParserPanelRead;
    public de.unisiegen.gtitool.ui.style.StyledWordParserPanel styledWordParserPanelWrite;
    // End of variables declaration//GEN-END:variables
 
}
