/*
 * AlgorithmWindowForm.java
 *
 * Created on 18. Februar 2009, 12:46
 */

package de.unisiegen.gtitool.ui.netbeans;

import de.unisiegen.gtitool.ui.swing.JGTIToggleButton;

import de.unisiegen.gtitool.ui.utils.AlgorithmDocument;
import javax.swing.JFrame;

/**
 *
 * @author  simon
 */
@SuppressWarnings("all")
public class AlgorithmWindowForm extends JFrame {

    private JGTIToggleButton toggleButton;
    
    /** Creates new form AlgorithmWindowForm */
    public AlgorithmWindowForm(java.awt.Frame parent, boolean modal, String algorithm, JGTIToggleButton toggleButton) {
        super();
        initComponents();

        this.jGTITextPaneAlgorithm.setDocument ( new AlgorithmDocument() );
        this.jGTITextPaneAlgorithm.setText(algorithm);
        this.jGTITextPaneAlgorithm.setHighlighter (null);
        this.toggleButton = toggleButton;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPaneAlgorithm = new javax.swing.JScrollPane();
        jGTITextPaneAlgorithm = new de.unisiegen.gtitool.ui.swing.JGTITextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/i18n/messages"); // NOI18N
        setTitle(bundle.getString("AlgorithmWindow.Title")); // NOI18N
        setAlwaysOnTop(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jGTITextPaneAlgorithm.setEditable(false);
        jScrollPaneAlgorithm.setViewportView(jGTITextPaneAlgorithm);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPaneAlgorithm, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-533)/2, (screenSize.height-330)/2, 533, 330);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.unisiegen.gtitool.ui.swing.JGTITextPane jGTITextPaneAlgorithm;
    private javax.swing.JScrollPane jScrollPaneAlgorithm;
    // End of variables declaration//GEN-END:variables

}
