/*
 * RegexNodeInfoPanel.java
 *
 * Created on 12. Dezember 2008, 10:31
 */

package de.unisiegen.gtitool.ui.netbeans;

/**
 *
 * @author Simon Meurer
 */
@SuppressWarnings("all")
public class RegexNodeInfoPanel extends javax.swing.JPanel {

    /**
     * The serial version uid.
     */
    private static final long serialVersionUID = -4243431767479790269L;
   
    /** Creates new form RegexNodeInfoPanel */
    public RegexNodeInfoPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        this.jGTILabelNullable = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        this.jScrollPaneNullable = new javax.swing.JScrollPane();
        this.jGTITextAreaNullable = new de.unisiegen.gtitool.ui.swing.JGTITextArea();
        this.jScrollPaneFirstpos = new javax.swing.JScrollPane();
        this.jGTITextAreaFirstpos = new de.unisiegen.gtitool.ui.swing.JGTITextArea();
        this.jGTILabelFirstpos = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        this.jGTILabelLastpos = new de.unisiegen.gtitool.ui.swing.JGTILabel();
        this.jScrollPaneLastpos = new javax.swing.JScrollPane();
        this.jGTITextAreaLastpos = new de.unisiegen.gtitool.ui.swing.JGTITextArea();
        this.jScrollPaneFollowpos = new javax.swing.JScrollPane();
        this.jGTITextAreaFollowpos = new de.unisiegen.gtitool.ui.swing.JGTITextArea();
        this.jGTILabelFollowpos = new de.unisiegen.gtitool.ui.swing.JGTILabel();

        setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/unisiegen/gtitool/ui/i18n/messages"); // NOI18N
        this.jGTILabelNullable.setText(bundle.getString("RegexNodeInfo.Nullable")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 10);
        add(this.jGTILabelNullable, gridBagConstraints);

        this.jGTITextAreaNullable.setColumns(20);
        this.jGTITextAreaNullable.setEditable(false);
        this.jGTITextAreaNullable.setRows(1);
        this.jScrollPaneNullable.setViewportView(this.jGTITextAreaNullable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        add(this.jScrollPaneNullable, gridBagConstraints);

        this.jGTITextAreaFirstpos.setColumns(20);
        this.jGTITextAreaFirstpos.setEditable(false);
        this.jGTITextAreaFirstpos.setRows(2);
        this.jScrollPaneFirstpos.setViewportView(this.jGTITextAreaFirstpos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        add(this.jScrollPaneFirstpos, gridBagConstraints);

        this.jGTILabelFirstpos.setText(bundle.getString("RegexNodeInfo.Firstpos")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        add(this.jGTILabelFirstpos, gridBagConstraints);

        this.jGTILabelLastpos.setText(bundle.getString("RegexNodeInfo.Lastpos")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        add(this.jGTILabelLastpos, gridBagConstraints);

        this.jGTITextAreaLastpos.setColumns(20);
        this.jGTITextAreaLastpos.setEditable(false);
        this.jGTITextAreaLastpos.setRows(2);
        this.jScrollPaneLastpos.setViewportView(this.jGTITextAreaLastpos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        add(this.jScrollPaneLastpos, gridBagConstraints);

        this.jGTITextAreaFollowpos.setColumns(20);
        this.jGTITextAreaFollowpos.setEditable(false);
        this.jGTITextAreaFollowpos.setRows(2);
        this.jScrollPaneFollowpos.setViewportView(this.jGTITextAreaFollowpos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 10);
        add(this.jScrollPaneFollowpos, gridBagConstraints);

        this.jGTILabelFollowpos.setText(bundle.getString("RegexNodeInfo.Followpos")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        add(this.jGTILabelFollowpos, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelFirstpos;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelFollowpos;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelLastpos;
    public de.unisiegen.gtitool.ui.swing.JGTILabel jGTILabelNullable;
    public de.unisiegen.gtitool.ui.swing.JGTITextArea jGTITextAreaFirstpos;
    public de.unisiegen.gtitool.ui.swing.JGTITextArea jGTITextAreaFollowpos;
    public de.unisiegen.gtitool.ui.swing.JGTITextArea jGTITextAreaLastpos;
    public de.unisiegen.gtitool.ui.swing.JGTITextArea jGTITextAreaNullable;
    public javax.swing.JScrollPane jScrollPaneFirstpos;
    public javax.swing.JScrollPane jScrollPaneFollowpos;
    public javax.swing.JScrollPane jScrollPaneLastpos;
    public javax.swing.JScrollPane jScrollPaneNullable;
    // End of variables declaration//GEN-END:variables

}
